// Code generated by weaver from model/. DO NOT EDIT.

// Package semconv holds the attribute keys and metric names defined in
// this module's telemetry registry (model/).
package semconv

import "go.opentelemetry.io/otel/attribute"

// Attributes.
const (
	// Number of items processed by a demo work unit.
	BasementDemoWorkItemCountKey = attribute.Key("basement.demo.work.item_count")
	// Outcome of a demo work unit.
	BasementDemoWorkResultKey = attribute.Key("basement.demo.work.result")
	// HTTP status code carried by the problem details.
	ProblemStatusKey = attribute.Key("problem.status")
	// RFC 9457 problem type URI of an error response.
	//
	// `unclassified` when the error response did not go through `problem.Write`.
	ProblemTypeKey = attribute.Key("problem.type")
)

// BasementDemoWorkItemCount returns a basement.demo.work.item_count attribute.
func BasementDemoWorkItemCount(val int) attribute.KeyValue {
	return BasementDemoWorkItemCountKey.Int(val)
}

// BasementDemoWorkResult returns a basement.demo.work.result attribute.
func BasementDemoWorkResult(val string) attribute.KeyValue {
	return BasementDemoWorkResultKey.String(val)
}

// Values of basement.demo.work.result.
var (
	// The work unit completed.
	BasementDemoWorkResultOK = BasementDemoWorkResultKey.String("ok")
	// The work unit failed.
	BasementDemoWorkResultError = BasementDemoWorkResultKey.String("error")
)

// ProblemStatus returns a problem.status attribute.
func ProblemStatus(val int) attribute.KeyValue {
	return ProblemStatusKey.Int(val)
}

// ProblemType returns a problem.type attribute.
func ProblemType(val string) attribute.KeyValue {
	return ProblemTypeKey.String(val)
}

// basement.demo.work.duration (histogram).
const (
	BasementDemoWorkDurationName        = "basement.demo.work.duration"
	BasementDemoWorkDurationUnit        = "s"
	BasementDemoWorkDurationDescription = "Duration of demo work units."
)

// basement.demo.work.items (counter).
const (
	BasementDemoWorkItemsName        = "basement.demo.work.items"
	BasementDemoWorkItemsUnit        = "{item}"
	BasementDemoWorkItemsDescription = "Number of items processed by demo work units."
)

// servicepack.http.server.problems (counter).
const (
	ServicepackHTTPServerProblemsName        = "servicepack.http.server.problems"
	ServicepackHTTPServerProblemsUnit        = "{problem}"
	ServicepackHTTPServerProblemsDescription = "Number of HTTP server error responses (status 400 and above)."
)
