apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "basement.fullname" . }}-config
  labels:
    {{- include "basement.labels" . | nindent 4 }}
data:
  app.yml: |
    server:
      port: {{ .Values.config.server.port }}
      disableTLS: {{ .Values.config.server.disableTLS }}
      disableTelemetry: {{ .Values.config.server.disableTelemetry }}
      logLevel: {{ .Values.config.server.logLevel | quote }}
